version: '3.8'
services:
  app:
    #image: node:19.2-alpine
    build: .
    command: sh -c "npm i && npm run dev"
    # command: node --inspect=0.0.0.0:9229 index.js
    ports:
      - 3000:3000
      - 9229:9229
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - APP_NAME=k8s-express-ex
      - USERNAME=alberto
      - PASSWORD=albertoPwd